version: '3'
services:
  couchdb:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${DB_USER}
      - COUCHDB_PASSWORD=${DB_PASS}
    volumes:
      - ./dbdata:/opt/couchdb/data

  storage-node:
    build: .
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: couchdb
    restart: on-failure
